### ISSUE TITLE
DENO_DIR cache *maybe* no longer works

### ISSUE THREAD

**Issue by hayd** [denoland/deno-lambda#116]
Previously

```
import type {
  Context,
  APIGatewayProxyEvent
} from "https://deno.land/x/lambda/mod.ts";
```
etc.

the deps and gen were correctly cached (from the layer and the function code), this seems to no longer be the case.

It's unclear to me if it's a zipping issue or due the filenames being renamed (now there's hashes in the name).

---

I'm not 100% sure this is an issue, but have a suspicion... needs investigate (and ideally a test).

**Comment by hayd** [comment]
Specifically deno.land/x/lambda should not be fetched during tests?

**Comment by hayd** [comment]
So, previously the `https://deno.land/x/lambda/mod.ts` and `types.d.ts` were prepopulated from the current dir (avoiding the fetch). This is no longer the case :/

I am not sure the best solution here... perhaps simply not using `https://deno.land/x/lambda/mod.ts` ? 😢

**Comment by hayd** [comment]
Use deno-lambda with docker is my recommendation for this.

Deno uses more opaque/clever caching for local file compiled assets than it once did. I haven't looked into this in a while / am not sure how much/if any is exposed so mv assets could work.

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
