### ISSUE TITLE
Working Directory is ignored in the Docker Image

### ISSUE THREAD

**Issue by wperron** [denoland/deno-lambda#121]
I have the following configuration in Terraform:
```hcl
resource "aws_lambda_function" "this" {
  # ...
  image_config {
    working_directory = "/var/task/foo/bar"
    command           = ["baz.handler"]
  }
}
```
but the bootstrap script seems to be ignoring the `working_directory` parameter and tries to import `/var/task/baz.js` instead of `/var/task/foo/bar/baz.js` - as a workaround I commented out the parameter and changed the command to `["foo/bar/baz.handler"]`

**Comment by hayd** [comment]
Atm `CMD ["foo/bar/baz.handler"]` is the way forward. In some sense that's not a workaround but has always been the way to reference files not at the top level.

It's unclear to me how to support working directory... i need to think about it a little more... what you are supposed to do with LAMBDA_TASK_ROOT vs WORKDIR? 🤔

**Comment by wperron** [comment]
We should run some tests with some of the default runtimes to see how they behave, that might enlighten us as to how to support workdir for the deno runtime.

**Comment by hayd** [comment]
Not looked into this but my suspicion is what should be done is cd into /var/task and realpath the WORKDIR (initial directory).
```
# realpath -m --relative-to="/var/task/" "/var/task/foo/bar/baz.handler"
foo/bar/baz.handler
```
and use this as the HANDLER (if WORKDIR=LAMBDA_TASK_ROOT then above is a noop).

However, for sure there will need to be DENO_DIR tweak (since it's relative atm, but shouldn't be really).

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
