### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by shellscape** [denoland/deno-lambda#149]
Howdy :wave: Just wondering if you had benchmarks for Deno performance on Lambda squirreled away you could share. Trying to convince a team to give this a shot and benchmarks was the first thing they asked for.

**Comment by Alon2303** [comment]
Hi @shellscape, What type of benchmarks are you hoping for?
thx

**Comment by kyeotic** [comment]
I would be interested in the following benchmarks, on a matrix of 128mb, 256mb, 512mb lambdas

* Cold Start; with echo response, no deps
* Warm Start; with echo response, no deps
* Fetch from dynamo; minimal deps
* Parse GraphQL query, generate response from hardcoded data

**Comment by shellscape** [comment]
@Alon2303 I think @kyeotic nailed some great ones.

**Comment by dzvon** [comment]
For you might be interested, they recently posted a new article ["Benchmarking AWS Lambda Cold Starts Across JavaScript Runtimes"](https://deno.com/blog/aws-lambda-coldstart-benchmarks).

**Comment by o-alexandrov** [comment]
In the article, Deno benchmarks using a Docker container.
Node.js 20 in a docker container is [2.36x times slower](https://maxday.github.io/lambda-perf/) to start than the provided by AWS Node.js 20 container (using .zip).

The article is good as an attempt to persuade AWS to start providing Deno runtime for better caching and leading to better cold starts.

However, using a custom Docker image for JavaScript with AWS Lambda probably accounts to 1% of the total AWS Lambda usage. It’s faster to use Lambda Layers than a custom Docker container
- Deno’s article is twisting the reality in an attempt to persuade using Deno over Node.js, whereas in 99% of cases the .zip with provided by AWS Node.js 20 is much faster to start than Deno

**Comment by soundstep** [comment]
Hi there, all that is very informative.

We're considering using AWS Lambda with the Deno runtime for a few large-scale projects, as we already have some code written in Deno, and this would help us avoid a complete rewrite in Node.js.

Performance is a key factor, but we're also concerned about other potential challenges, especially at the enterprise level. Are there any issues we should be aware of, such as frequent API changes, limitations within the Deno runtime, or potential lack of support in the coming years, any shortcomings?

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
