### ISSUE TITLE
Possible to deploy with Pulumi?

### ISSUE THREAD

**Issue by ProdigySim** [denoland/deno-lambda#155]
I'm trying to give this lambda runtime a go on Pulumi, which should theoretically be similar to AWS-CDK but I'm not sure they support all the constructs necessary.

I can write something like:

```typescript
const denoRuntime = await aws.serverlessrepository.getApplication({
    applicationId: "arn:aws:serverlessrepo:us-east-1:390065572566:applications/deno",
    semanticVersion: "1.16.0",
  });
```
To get the runtime application, but it's not clear if there's a way to actually create/clone this application and produce a layer ARN.

(Apologies for this pretty open support request, I'm kind of new to all of these tools)

**Comment by hayd** [comment]
It seems pulumi uses terraform so we need to work out how to use that with SAR... 😬 (I wish this was better documented as it seems like this is likely straightforward!)

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
