### ISSUE TITLE
Improve error message for test_missing_handler.json

### ISSUE THREAD

**Issue by hayd** [denoland/deno-lambda#157]
Revert:
https://github.com/hayd/deno-lambda/pull/156/commits/31da6a2921356c1c65a4338ed79f2ccd91f4beb5

I've not investigated the issue, but assuming there was a minor api change that affected our error handing [here](https://github.com/hayd/deno-lambda/blob/master/runtime/bootstrap#L103-L104).

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
