### ISSUE TITLE
allow option to run with `--check`

### ISSUE THREAD

**Issue by kyeotic** [denoland/deno-lambda#177]
Deno has a flag to run without [type-checking](https://deno.land/manual/typescript/overview#type-checking), which is useful for lambdas that have already been type-checked. There are already several `DENO` ENV VARs to configure behavior, a `DENO_NOCHECK` or more flexible `DENO_FLAGS` would be useful here.

**Comment by hayd** [comment]
Currently --no-check is always passed:

https://github.com/hayd/deno-lambda/blob/master/runtime/bootstrap#L22

happy to submission of this, BUT I think --no-check is deprecated and deno is moving to --check (so flag should be DENO_CHECK). Potentially we should support --check=all etc.

https://github.com/denoland/deno/pull/14691

**Comment by kyeotic** [comment]
Sounds good

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
