### ISSUE TITLE
import_map causes module not found

### ISSUE THREAD

**Issue by kyeotic** [denoland/deno-lambda#179]
I have an otherwise working application that fails if I try to use an import map; specifically the kind of import maps generated by [trex](https://nicedoc.io/crewdevio/Trex). I have created a minimal repro of the issue with [this repository](https://github.com/kyeotic/deno-lambda-repro). Here is [the working version](https://github.com/kyeotic/deno-lambda-repro/tree/working-deps) without the import map.

The failure it produces is
```
2022-05-30T13:22:56.089-07:00 | error: Module not found "file:///var/task/tmp/runtime.js".
-- | --
  | 2022-05-30T13:22:56.133-07:00 | error: deno exited
  | 2022-05-30T13:22:56.219-07:00 | START RequestId: ee82b3a3-6dc4-4f7b-ae89-d7646649862d Version: $LATEST
  | 2022-05-30T13:22:56.822-07:00 | error: Module not found "file:///var/task/tmp/runtime.js".
  | 2022-05-30T13:22:57.303-07:00 | error: deno exited
  | 2022-05-30T13:22:57.443-07:00 | END RequestId: ee82b3a3-6dc4-4f7b-ae89-d7646649862d
  | 2022-05-30T13:22:57.443-07:00 | REPORT RequestId: ee82b3a3-6dc4-4f7b-ae89-d7646649862d Duration: 1222.96 ms Billed Duration: 1223 ms Memory Size: 128 MB Max Memory Used: 12 MB
  | 2022-05-30T13:22:57.443-07:00 | Unknown application error occurred Unhandled
  | 2022-05-30T13:22:57.904-07:00 | error: Module not found "file:///var/task/tmp/runtime.js".
  | 2022-05-30T13:22:57.945-07:00 | error: deno exited
```

**Comment by hayd** [comment]
Thanks, I haven't really used terraform so this is interesting!
Could you share the steps how you generated these files? or did you create them all?

---

That error is definitely bad. 🤔 

Some thoughts from reading the scripts:

Can you remove the `/dev/null`s from this file and see if there is any helpful output?
https://github.com/kyeotic/deno-lambda-repro/blob/main/scripts/bundle_lambda#L14-L32

Also, potentially worth trying the bundle method/line instead?

**Comment by kyeotic** [comment]
The dev/null pipes just hide all the individual file noise. You can comment them out and see no errors are being hidden. Again, this exact setup works without the import map; just replace the import with one directly to the url.

You have to have terraform installed to use these, but the deploy step is simply

```
// from the project root folder
./scripts/deploy dev // (or whatever)
```

You can run `bundle_lambda` on its own if you just want to see the zip it produces, but deploy will run that on its own. As far as how they were generated... I've been using terraform for a while, they've been copied and developed over a few years. The core "deno lambda" bundling logic came from this repo though, its nothing special except for the additional of the import map.

**Comment by hayd** [comment]
Related from #176:

> The failure to transform DENO_IMPORTMAP = "./import_map.json" the way $LAMBDA_TASK_ROOT/$HANDLER_FILE is possibly a bug, but I don't think it is related.

**Comment by gm112** [comment]
The fix may possibly be to add a mapping of `$LAMBDA_TASK_ROOT` as a redirect to `./`, possibly? Can definitely confirm this is reproduceable with an empty zip file and a lambda function that is baked with the provided Deno runtime. Removing the import_map from the env var actually remedies the problem.

Bundling works around this problem for now.

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
