### ISSUE TITLE
Add terraform example

### ISSUE THREAD

**Issue by hayd** [denoland/deno-lambda#180]
https://github.com/kyeotic/deno-lambda-repro

related #155

**Comment by Damola12345** [comment]
hi @hayd  can i help you with this task ?

**Comment by hayd** [comment]
@Damola12345 definitely! Please see the other example directories to what this might look like: and then it'd be a hello world script but with terraform?

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
