### ISSUE TITLE
DENO_PERMISSIONS - restrict net access only to  certain host

### ISSUE THREAD

**Issue by anandjbangad** [denoland/deno-lambda#212]
Hi, I am adding environment variable DENO_PERMISSIONS=--allow-net=google.com,jsonplaceholder.typicode.com,deno.land --allow-env. I just want to allow only 3 hosts. I keep getting an error stating error: Uncaught PermissionDenied: Requires net access to "127.0.0.1:9001", run again with the --allow-net flag. 

What am I doing wrong ?

**Comment by hayd** [comment]
if you add 127.0.0.1 (localhost) it should work.

that localhost url is required for the backend machinery of how lambda processes messages.

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
