### ISSUE TITLE
Is it possible to use npm DefinitelyTyped types directly instead of this repo?

### ISSUE THREAD

**Issue by pjroth** [denoland/deno-lambda#219]
To have types in my code, is it not possible to do something like the following:
```
import {
    Context
} from "npm:@types/aws-lambda";
```

Sorry, this might be my ignorance about Deno and the differences in imports.  I tried this code and it doesn't fail, although my IDE (IntelliJ) fails to click into the code source (ctrl-+ into a type doesn't go to the type definition), although code completion and inline type checking seems to work properly (incorrect properties colored red/etc). 

Thank you!

**Comment by hayd** [comment]
I _think_ this should work too / might be better (get a more specific version) !

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
