### ISSUE TITLE
runtime compile error with deno-lambda example

### ISSUE THREAD

**Issue by cknight** [denoland/deno-lambda#232]
I've followed the [SAR quick-start](https://github.com/hayd/deno-lambda/blob/master/QUICK-START.md) guide in the repo and deployed the deno layer.  I've then created a new function from scratch, chosen custom runtime and added the deno layer as per the instructions.  I've uploaded the [latest code](https://github.com/hayd/deno-lambda/releases) (deno-lambda-example.zip v1.32.5) to the function.  However when I run a test for the first time I get the following error:

```shell
Response
{
  "errorMessage": "unable to compile hello.ts",
  "errorType": "InitException"
}

Function Logs
error: Module not found "file:///var/runtime/mod.ts".
at file:///var/task/hello.ts:5:8
error: unable to compile hello.ts
error: Module not found "file:///var/runtime/mod.ts".
at file:///var/task/hello.ts:5:8
error: unable to compile hello.ts
START RequestId: 170ee5c6-39c3-45d5-b469-9571a14a936e Version: $LATEST
Unknown application error occurred
Runtime.Unknown
END RequestId: 170ee5c6-39c3-45d5-b469-9571a14a936e
```

The import it is failing on is this code (unmodified from the zip file):
```ts
import {
  APIGatewayProxyEventV2,
  APIGatewayProxyResultV2,
  Context,
} from "../runtime/mod.ts";
```
Looking at the code in the repo and examining the zip files, there is no mod.ts file at the root of `deno-lambda-example.zip` (which would be uploaded to `/var/runtime` I believe).

Looking at the [generation of the zip files](https://github.com/hayd/deno-lambda/blob/master/runtime/artifacts), it would appear that mod.ts should be referenced by it's full URL (`https://deno.land/x/lambda/mod.ts`) and retrieved from the deno cache in `.deno-dir`. Thus, if I update the import in `hello.ts` to:
```ts
import {
  APIGatewayProxyEvent,
  APIGatewayProxyResult,
  Context
} from "https://deno.land/x/lambda/mod.ts";
```

I get it to work, but with a slow init/cold start as it is downloading the dependencies from scratch rather than using the cached copies in the `.deno-dir` directory included in the deno-lambda-example.zip.  Output from this change:

```shell
Function Logs
Download https://deno.land/x/lambda/mod.ts
Warning Implicitly using latest version (1.32.5) for https://deno.land/x/lambda/mod.ts
Download https://deno.land/x/lambda@1.32.5/mod.ts
Download https://deno.land/x/lambda@1.32.5/types.d.ts
START RequestId: 3a401818-3eb4-46c5-944e-c0cae35c773b Version: $LATEST
END RequestId: 3a401818-3eb4-46c5-944e-c0cae35c773b
REPORT RequestId: 3a401818-3eb4-46c5-944e-c0cae35c773b	Duration: 57.32 ms	Billed Duration: 1281 ms	Memory Size: 128 MB	Max Memory Used: 86 MB	Init Duration: 1222.95 ms
```

Where am I going wrong?  Why isn't the `.deno-dir` cache being used?  Any help most appreciated.

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
