### ISSUE TITLE
Red herring "error: missing deno executable"

### ISSUE THREAD

**Issue by denizdogan** [denoland/deno-lambda#234]
https://github.com/hayd/deno-lambda/blob/d6aa165b66868a49b282ba2e79abf3430ff87d5e/runtime/bootstrap#L248

If the Deno application exits abnormally for any reason, the output will say "error: missing deno executable".

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
