### ISSUE TITLE
Adding deno flag --watch dosent work in dev environment

### ISSUE THREAD

**Issue by iamkhalidbashir** [denoland/deno-lambda#241]
We want to use deno lambda contianer for dev enviroment.
But adding --watch flag leads to a halt in rquest.

```bash
Watcher File change detected! Restarting!
START RequestId: 1ff9ae42-8461-4989-9c38-2fd3a98347e2 Version: $LATEST
```
After this nothing happens

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
