### ISSUE TITLE
Automate tagging

### ISSUE THREAD

**Issue by dsherret** [denoland/deno-lambda#276]
> Create a release with the version number (without v prefix).

This step in the release process is annoying to do and error prone.

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
