### ISSUE TITLE
Support `index.mjs` and `index.js` entrypoints

### ISSUE THREAD

**Issue by littledivy** [denoland/deno-lambda#282]
Currently `index.handler` only works with `index.ts`. `index.mjs` support will make this layer work OOTB with `open-next` build outputs

**Comment by igorzi** [comment]
This should already work by setting Lambda `HANDLER_EXT` env variable to `mjs`.

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
