### ISSUE TITLE
Add Deno to Lambda perf.

### ISSUE THREAD

**Issue by soundstep** [denoland/deno-lambda#306]
Hi, I'm trying to add Deno to this repo:

https://github.com/maxday/lambda-perf/pull/1467

I'm not a Rust developer, I'm doing what I can there.

Can you confirm the deno layer can use these [2 architectures](https://github.com/maxday/lambda-perf/pull/1467/files#diff-ffa5b716b5a57837f7929dfcca4b4dfdeb97210a7fd5a12d2f1978846d6f1743R354)?

Any help is appreciated on this pull request, I can give you access to the forced repo.

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).
